insert into district values(1,'Bagalkot');
insert into district values(2,'Bengaluru Urban');
insert into district values(3,'Bengaluru Rural');
insert into district values(4,'Belgavi');
insert into district values(5,'Bellary');
insert into district values(6,'Bidar');
insert into district values(7,'Vijayapura');
insert into district values(8,'Chamarajanagar');
insert into district values(9,'Chikballapur');
insert into district values(10,'Chikkamagaluru');
insert into district values(11,'Chitradurga');
insert into district values(12,'Dakshina Kannada');
insert into district values(13,'Davanagere');
insert into district values(14,'Dharwad');
insert into district values(15,'Gadag');
insert into district values(16,'Kalaburagi');
insert into district values(17,'Hassan');
insert into district values(18,'Haveri');
insert into district values(19,'Kodagu');
insert into district values(20,'Kolar');
insert into district values(21,'Koppal');
insert into district values(22,'Mandya');
insert into district values(23,'Mysuru');
insert into district values(24,'Raichur');
insert into district values(25,'Ramanagara');
insert into district values(26,'Shivamogga');
insert into district values(27,'Tumakuru');
insert into district values(28,'Udupi');
insert into district values(29,'Uttara Kannada');
insert into district values(30,'Yadgir');
