insert into hospital values(1,'Bagalkote District Hospital FRU',1);
insert into hospital values(2,'Bowring Lady Curzon',2);
insert into hospital values(3,'ESIC Modern Hospital',2);
insert into hospital values(4,'HSIS Goshiya',2);
insert into hospital values(5,'Indranagar General Hospital',2);
insert into hospital values(6,'Jayanagar General Hospital',2);
insert into hospital values(7,'KC General Hospital',2);
insert into hospital values(8,'Vanivilas Hospital',2);
insert into hospital values(9,'Victoria Hospital',2);
insert into hospital values(10,'Belgaum District Hospital',4);
insert into hospital values(11,'Bellary District Hospital',5);
insert into hospital values(12,'VIMS Bellary Medical College',5);
insert into hospital values(13,'Bidar District Hospital',6);
insert into hospital values(14,'Vijiyapura District Hospital',7);
insert into hospital values(15,'Chamarajanagar District Hospital',8);
insert into hospital values(16,'Chikkaballapur District Hospital',9);
insert into hospital values(17,'Chikmagaluru District Hospital',10);
insert into hospital values(18,'Chitradurga District Hospital',11);
insert into hospital values(19,'Lady Goshan Hospital',12);
insert into hospital values(20,'Wenlock Hospital',12);
insert into hospital values(21,'Davangere District Hospital',13);
insert into hospital values(22,'Davangere Women and Children DH',13);
insert into hospital values(23,'Dharwad District Hospital FRU',14);
insert into hospital values(24,'Hubli KIMS District Hospital',14);
insert into hospital values(25,'Gadag District Hospital',15);
insert into hospital values(26,'Gulbarga District Hospital FRU',16);
insert into hospital values(27,'Hassan District Hospital',17);
insert into hospital values(28,'Haveri District Hospital FRU',18);
insert into hospital values(29,'Kodagu District Hospital FRU',19);
insert into hospital values(30,'Kolar District Hospital FRU',20);
insert into hospital values(31,'Koppal District Hospital FRU',21);
insert into hospital values(32,'Mandya District Hospital',22);
insert into hospital values(33,'Cheluvamba Hospital MYsore DH',23);
insert into hospital values(34,'KR Hospital Mysore DH',23);
insert into hospital values(35,'Raichur District Hospital',24);
insert into hospital values(36,'Ramanagara District Hospital FRU',25);
insert into hospital values(37,'Shikaripura DH FRU',26);
insert into hospital values(38,'Shimoga District Hospital',26);
insert into hospital values(39,'Tumkur District Hospital FRU',27);
insert into hospital values(40,'Udupi District Hospital FRU',28);
insert into hospital values(41,'Uttara Kannada District Hospital FRU',29);
insert into hospital values(42,'Yadgir District Hospital FRU',30);
